services:
  receipt-processor:
    container_name: receipt_processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HOST_PORT}:${APP_PORT}
    expose:
      - ${ADMIN_PORT}
    deploy:
      update_config:
        order: start-first
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${ADMIN_PORT}/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
