version: '3.8'

services:
  receipt-processor:
    container_name: receipt_processor
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${HOST_PORT}:${APP_PORT}
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
